version: 2
updates:
  # Maintain dependencies for Webclient
  - package-ecosystem: "npm"
    directory: "/webclient"
    schedule:
      interval: "daily"
  # Maintain dependencies for Server
  - package-ecosystem: "gomod" 
    directory: "/server"
    schedule:
      interval: "daily"
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"