version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod" 
    directory: "/app"
    schedule:
      interval: "daily"
