name: Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version-file: 'webclient/.nvmrc'

      - name: Build Server
        run: cd server && go build -v ./...

      - name: Test Server
        run: |
          cd server
          go test -coverprofile=coverage.out ./... -coverpkg=./... -timeout 100ms -race

      - name: Fetch Webclient Dependencies
        run: |
          cd webclient
          npm ci

      - name: Run Webclient Tests
        run: |
          cd webclient
          npm run build
          npm run test:coverage

      - name: Publish to Codecov
        uses: codecov/codecov-action@v3