name: Run Linters
on:
  pull_request_target:
    branches: [ "main" ]
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: 'webclient/.nvmrc'
      - name: Fetch Webclient Dependencies
        run: |
          cd webclient
          npm ci
      - name: Run ESLint
        uses: reviewdog/action-eslint@v1
        with:
          fail_on_error: true
          workdir: 'webclient/'
      - name: Run Prettier
        uses: EPMatt/reviewdog-action-prettier@v1
        with:
          workdir: 'webclient/'