name: Build and Test App

on:
  pull_request_target:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: cd server && go build -v ./...

      - name: Test
        id: test
        run: |
          cd server
          go test -coverprofile=coverage.out ./... -coverpkg=./... -timeout 100ms -race
      - uses: codecov/codecov-action@v3