name: Build and Test App

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - run: cd app

      - name: Build
        run: go build -v ./...

      - name: Test
        id: test
        run: |
          go test  -v ./... -coverpkg=./... -timeout 100ms -race
          OUTPUT=$(go tool cover -func=coverage | tail -1)
          echo "::set-output name=result::$OUTPUT"

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          message: |
            ```
            ${{ steps.test.outputs.result }}
            ```